# Generated by Django 3.2.12 on 2022-05-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='follower',
            new_name='following_user_id',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.UniqueConstraint(fields=('user_id', 'following_user_id'), name='unique_followers'),
        ),
    ]
