# Generated by Django 3.2.12 on 2022-05-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default='profilePictures/default.png', null=True, upload_to='profilePictures/'),
        ),
    ]
